version: "3"
services:
  kms2:
    build: .
    restart: always
    environment:
      - "PORT=3000"
      - "NEO4J_URI=bolt://neo4j:7687"
      - "NEO4J_USER=neo4j"
      - "NEO4J_PASSWORD=password"
    ports:
      - "3000:3000"
  neo4j:
    image: neo4j:3.5.8
    environment:
      - "NEO4J_AUTH=none"
    ports:
      - "7687:7687" # Bolt
      - "7474:7474" # User Interface
